/**
 * Shared utilities for platform template modules.
 * Eliminates boilerplate across qoder/, codebuddy/, droid/, cursor/, gemini/, kiro/ index.ts files.
 */

import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export interface AgentTemplate {
  name: string;
  content: string;
}

export interface HookTemplate {
  targetPath: string;
  content: string;
}

const GENERATED_NAME_SUFFIXES = [
  "start",
  "continue",
  "finish-work",
  "before-dev",
  "brainstorm",
  "break-loop",
  "check",
  "update-spec",
  "implement",
  "research",
  "meta",
  "spec-bootstrap",
  "session-insight",
  "channel",
] as const;

const GENERATED_NAME_RE = new RegExp(
  `\\btrellis-(${GENERATED_NAME_SUFFIXES.join("|")})\\b`,
  "g",
);

export function toCviautoGeneratedName(name: string): string {
  if (name === "trellis") {
    return "cviauto";
  }
  return name.replace(/^trellis-/, "cviauto-");
}

export function toCviautoGeneratedContent(content: string): string {
  return content
    .replace(GENERATED_NAME_RE, "cviauto-$1")
    .replace(/\bTrellis\b/g, "Cviauto")
    .replace(/\btrellis init\b/g, "cviauto init")
    .replace(/\btrellis update\b/g, "cviauto update")
    .replace(/\btrellis upgrade\b/g, "cviauto upgrade")
    .replace(/\btrellis uninstall\b/g, "cviauto uninstall")
    .replace(/\btrellis workflow\b/g, "cviauto workflow")
    .replace(/\btrellis channel\b/g, "cviauto channel")
    .replace(/\btrellis mem\b/g, "cviauto mem");
}

export interface TemplateReader {
  readTemplate: (relativePath: string) => string;
  listFiles: (dir: string) => string[];
  listMdAgents: (dir?: string) => AgentTemplate[];
  listJsonAgents: (dir?: string) => AgentTemplate[];
  getSettings: (filename?: string) => HookTemplate;
  getConfig: (filename: string) => string;
}

/**
 * Create a template reader bound to the caller's directory.
 * Usage: `const { readTemplate, listMdAgents, getSettings } = createTemplateReader(import.meta.url);`
 */
export function createTemplateReader(importMetaUrl: string): TemplateReader {
  const __dirname = dirname(fileURLToPath(importMetaUrl));

  function readTemplate(relativePath: string): string {
    return readFileSync(join(__dirname, relativePath), "utf-8");
  }

  function listFiles(dir: string): string[] {
    try {
      return readdirSync(join(__dirname, dir)).sort();
    } catch {
      return [];
    }
  }

  /** Read all .md agent files from a subdirectory */
  function listMdAgents(dir = "agents"): AgentTemplate[] {
    return listFiles(dir)
      .filter((f) => f.endsWith(".md"))
      .map((f) => ({
        name: toCviautoGeneratedName(f.replace(".md", "")),
        content: toCviautoGeneratedContent(readTemplate(`${dir}/${f}`)),
      }));
  }

  /** Read all .json agent files from a subdirectory (Kiro) */
  function listJsonAgents(dir = "agents"): AgentTemplate[] {
    return listFiles(dir)
      .filter((f) => f.endsWith(".json"))
      .map((f) => ({
        name: toCviautoGeneratedName(f.replace(".json", "")),
        content: toCviautoGeneratedContent(readTemplate(`${dir}/${f}`)),
      }));
  }

  /** Read settings.json and return as HookTemplate */
  function getSettings(filename = "settings.json"): HookTemplate {
    return { targetPath: filename, content: readTemplate(filename) };
  }

  /** Read a config file and return raw string */
  function getConfig(filename: string): string {
    return readTemplate(filename);
  }

  return {
    readTemplate,
    listFiles,
    listMdAgents,
    listJsonAgents,
    getSettings,
    getConfig,
  };
}
